Repository andela/vidar-ah-backend, pull requests merged in 2019-03, with the labels that each got.

#16 #164366326 Implement user login with email
  controllers/user.js
  middleware/auth.js
  middleware/validation.js
  package-lock.json
  package.json
  routes/v1.js
  test/index.js
  test/login.spec.js
  test/profile.spec.js
Labels: Work in Progress

#25 #164366326: implement user login with email
  .eslintignore
  controllers/user.js
  doc.json
  middleware/validation.js
  middleware/verifyUser.js
  package-lock.json
  package.json
  routes/v1.js
  test/helpers/userDummyData.js
  test/index.js
  test/login.spec.js
Labels: Ready to merge, Tested in staging

#22 #164139684: Enable social login via Google and Facebook
  .travis.yml
  auth/passport.js
  doc.json
  index.js
  migrations/20190305153026-make-password-accept-null.js
  models/User.js
  package-lock.json
  package.json
  routes/v1.js
  test/index.js
  test/socialLoginSpec.js
Labels: Ready to merge, Tested in staging

#14 #164139686 Creating an article
  .gitignore
  .travis.yml
  README.md
  controllers/articles.js
  controllers/user.js
  doc.json
  helpers/slug.js
  helpers/trimArticle.js
  middleware/addImage.js
  middleware/auth.js
  middleware/generateSlug.js
  middleware/validation.js
  migrations/20190305085324-create-article.js
  migrations/20190312203553-add-userId.js
  models/User.js
  models/article.js
  package-lock.json
  package.json
  routes/v1.js
  test/article.spec.js
  test/helpers/dummyData.js
  test/helpers/updateVerifiedStatus.js
  test/index.js
Labels: Ready to merge, Tested in staging

#21 #164139683 Add password reset feature
  controllers/user.js
  doc.json
  helpers/emails.js
  helpers/user.js
  middleware/validation.js
  middleware/verifyUser.js
  migrations/20190305110744-password-reset.js
  migrations/20190312203553-add-userId.js
  models/User.js
  package-lock.json
  routes/v1.js
  test/helpers/userDummyData.js
  test/index.js
  test/login.spec.js
  test/resetpassword.spec.js
Labels: TTL review needed

#28 #164603412 Create category for articles
  controllers/category.js
  doc.json
  middleware/auth.js
  middleware/validation.js
  migrations/20190313193812-create-category.js
  migrations/20190313195119-add_category_Id_to_article.js
  models/article.js
  models/category.js
  routes/v1.js
  test/article.spec.js
  test/category.spec.js
  test/helpers/categoryDummyData.js
  test/helpers/userDummyData.js
  test/index.js
  test/login.spec.js
Labels: Peer review complete, TTL review needed, Tested in staging

#29 #164541932: Update and delete an article
  controllers/articles.js
  doc.json
  middleware/validation.js
  package-lock.json
  package.json
  routes/v1.js
  test/article.spec.js
  test/helpers/articleDummyData.js
  test/helpers/userDummyData.js
  test/index.js
  test/login.spec.js
  test/socialLoginSpec.js
Labels: Peer review complete, Tested in staging

#34 #164595750 Add pre-commit hook with husky
  package-lock.json
  package.json
Labels: Peer review complete, TTL review needed

#35 #164139695 Add search and filter functionality
  .babelrc
  controllers/articles.js
  controllers/user.js
  helpers/paginate.js
  middleware/validation.js
  migrations/20190314104937-insert-default-category.js
  migrations/20190319105746-add-indexes.js
  models/article.js
  package-lock.json
  package.json
  routes/v1.js
  test/article.spec.js
  test/category.spec.js
  test/helpers/getVerificationId.js
  test/helpers/userDummyData.js
  test/login.spec.js
  test/profile.spec.js
  test/resetpassword.spec.js
  test/updateVerifiedStatusHelper.spec.js
  test/user.spec.js
Labels: TTL review needed

#32 #164139690 Add feature to follow and unfollow users
  controllers/follow.js
  doc.json
  middleware/follow.js
  migrations/20190314173143-create-follows.js
  models/User.js
  models/follows.js
  package-lock.json
  routes/v1.js
  test/follow.spec.js
  test/helpers/userDetails.js
  test/helpers/userDummyData.js
  test/index.js
Labels: Peer review complete, TTL review needed

#31 #164139688: Comment on articles
  controllers/comment.js
  doc.json
  middleware/validation.js
  migrations/20190313092713-create-comment.js
  models/User.js
  models/article.js
  models/comment.js
  package-lock.json
  routes/v1.js
  test/comment.spec.js
  test/helpers/articleDummyData.js
  test/helpers/commentDummyData.js
  test/helpers/dummyData.js
  test/helpers/userDummyData.js
  test/index.js
Labels: TTL review needed, Tested in staging

#30 #164139687 Add ratings to an article
  .eslintrc.json
  README.md
  controllers/articles.js
  doc.json
  middleware/checkIfArticleExist.js
  middleware/validation.js
  migrations/20190313152910-create-ratings.js
  models/article.js
  models/ratings.js
  package-lock.json
  routes/v1.js
  test/article.spec.js
  test/helpers/articleDummyData.js
  test/helpers/ratingDummyData.js
  test/helpers/userDummyData.js
  test/index.js
  test/rating.spec.js
Labels: Peer review complete, TTL review needed, Tested in staging

#41 164139701 Add reading stats feature
  controllers/articles.js
  controllers/user.js
  middleware/auth.js
  migrations/20190320101322-create-stats.js
  models/User.js
  models/article.js
  models/stats.js
  routes/v1.js
  test/helpers/dummyData.js
  test/helpers/userDummyData.js
  test/index.js
  test/login.spec.js
  test/stats.spec.js
Labels: Peer review complete, TTL review needed

#36 #164693398 Add the feature for users to be able to get all articles with pagination
  controllers/articles.js
  middleware/validation.js
  migrations/20190305085324-create-article.js
  models/article.js
  models/comment.js
  routes/v1.js
  test/article.spec.js
  test/stats.spec.js
Labels: TTL review needed

#42 #164139689: Like or dislike an article
  controllers/articles.js
  controllers/user.js
  doc.json
  middleware/validation.js
  migrations/20190319124843-create-reaction.js
  models/article.js
  models/reaction.js
  package-lock.json
  routes/v1.js
  test/article.spec.js
  test/helpers/articleDummyData.js
Labels: TTL review needed, Tested in staging

#39 #164693379 Create, update and delete category by admin and super admin
  controllers/category.js
  index.js
  middleware/auth.js
  middleware/verifyCategoryId.js
  middleware/verifyUser.js
  migrations/20190228194917-create-user.js
  models/User.js
  routes/v1.js
  seeders/createSuperAdmin.js
  test/article.spec.js
  test/category.spec.js
  test/helpers/assignRole.js
  test/helpers/categoryDummyData.js
  test/helpers/userDummyData.js
  test/index.js
  test/likeComment.spec.js
  test/login.spec.js
  test/rating.spec.js
  test/stats.spec.js
Labels: TTL review needed, Tested in staging
