Repository andela/vidar-ah-backend, pull requests merged in 2019-04, with the labels that each got.

#43 #164693172: Update user's profile image
  controllers/articles.js
  controllers/profile.js
  controllers/user.js
  helpers/splitName.js
  middleware/addImage.js
  middleware/validation.js
  migrations/20190319000245-addProfileImage.js
  models/User.js
  package-lock.json
  routes/v1.js
  test/article.spec.js
  test/assets/testImage.jpg
  test/helpers/userDummyData.js
  test/index.js
  test/profile.spec.js
Labels: Ready to merge, TTL review needed, Tested in staging

#50 #165380523 Redirect to frontend on successful social auth request
  package-lock.json
  routes/v1.js
  test/article.spec.js
Labels: TTL review needed

#54 #165410830 Return reaction count along with an article
  controllers/articles.js
  models/article.js
  test/article.spec.js
Labels: TTL review needed

#53 #164212349: Fix the user model to store user's interests
  controllers/profile.js
  controllers/user.js
  middleware/validation.js
  migrations/20190417100155-interest.js
  models/User.js
  package-lock.json
  package.json
  routes/v1.js
  test/article.spec.js
  test/comment.spec.js
  test/helpers/userDummyData.js
  test/profile.spec.js
  test/stats.spec.js
Labels: TTL review needed

#56 #165518152 Return relevant information from authentication and articles
  controllers/articles.js
  controllers/user.js
Labels: TTL review needed

#55 #165345758 Implement functionality to get user's stats
  controllers/follow.js
  controllers/user.js
  models/User.js
  package-lock.json
  package.json
  routes/v1.js
  test/follow.spec.js
  test/user.spec.js
Labels: Ready to merge, TTL review needed

#59 #164139699 Add functionality to report articles
  controllers/reports.js
  controllers/user.js
  middleware/validation.js
  migrations/20190424091606-create-reports.js
  models/article.js
  models/reports.js
  routes/v1.js
  test/helpers/reportsDummyData.js
  test/index.js
  test/reports.spec.js
Labels: TTL review needed

#60 #165579357: Fix endpoint to get all articles.
  controllers/articles.js
  test/article.spec.js
Labels: TTL review needed

#61 #165596222 Remove payload from url params to request body
  controllers/articles.js
  middleware/follow.js
  middleware/validation.js
  routes/v1.js
  test/article.spec.js
  test/follow.spec.js
  test/user.spec.js
Labels: TTL review needed

#64 #165674559 Fix social authentication logic to accommodate unique usernames
  auth/passport.js
Labels: TTL review needed
